Feature/mark custom types
pydantic/bump-pydantic pull request #116
Opened 2023-08-10 15:05 UTC by JensHeinrich

2023-08-10 15:06 UTC, JensHeinrich commented
- [ ] Rebase and reorder to make the "Fixes" commit the last commit after fixing the feature

2023-08-11 17:25 UTC, slafs commented
Nice! Thank you. This will be useful for us too! 🙇 (haven't reviewed this PR though)

Just noticed that the rule code should probably be `BP009` (or `BP011` maybe). The last current working one is `BP008`, but `BP009` and `BP010` are only mentioned in the README, they are not-implemented and commented out in the README. Looks like the last time a new mod was added (BP008), Marcelo incremented the number of commented out mods and used first "free" one.

2023-08-18 12:36 UTC, JensHeinrich commented
> Nice! Thank you. This will be useful for us too! 🙇 (haven't reviewed this PR though)
> 
> Just noticed that the rule code should probably be `BP009` (or `BP011` maybe). The last current working one is `BP008`, but `BP009` and `BP010` are only mentioned in the README, they are not-implemented and commented out in the README. Looks like the last time a new mod was added (BP008), Marcelo incremented the number of commented out mods and used first "free" one. See #90.

Ok, thought I would just append to the commented one^^

2023-09-04 11:55 UTC, JensHeinrich commented
> Nice! Thank you. This will be useful for us too! 🙇 (haven't reviewed this PR though)
> 
> Just noticed that the rule code should probably be `BP009` (or `BP011` maybe). The last current working one is `BP008`, but `BP009` and `BP010` are only mentioned in the README, they are not-implemented and commented out in the README. Looks like the last time a new mod was added (BP008), Marcelo incremented the number of commented out mods and used first "free" one. See #90.

Updated the numbering

2023-09-18 13:36 UTC, Kludex requested changes
We need to add a test for when there's already a TODO comment.

2023-09-18 13:36 UTC, Kludex commented on README.md
> +### BP009: Mark pydantic "protocol" functions in custom types with proper TODOs
```suggestion
### BP009: Mark Pydantic "protocol" functions in custom types with proper TODOs
```

2023-09-18 13:36 UTC, Kludex commented on README.md
> +        return
```suggestion
```

2023-09-18 13:36 UTC, Kludex commented on README.md
> +    ):
```suggestion
    def __modify_schema__(cls, field_schema, field):
```

2023-09-18 13:36 UTC, Kludex commented on README.md
> +    ):
```suggestion
    def __modify_schema__(cls, field_schema, field):
```

2023-09-18 13:36 UTC, Kludex commented on README.md
> +
```suggestion
```

2023-09-18 13:36 UTC, Kludex commented on bump_pydantic/codemods/__init__.py
> +    """Mark pydantic 'protocol' functions in custom types with proper TODOs"""
```suggestion
    '''Mark Pydantic "protocol" functions in custom types with proper TODOs.'''
```

2023-09-18 13:39 UTC, Kludex commented on README.md
> +        return
```suggestion
```

2023-09-18 13:58 UTC, Kludex approved these changes

2023-09-18 14:01 UTC, merged