✨ Add ignore patterns
pydantic/bump-pydantic pull request #92
Opened 2023-07-13 09:06 UTC by lemonyte

Allows the user to specify glob patterns to ignore when scanning for source files.

- Closes #57 

Example usage:

```bash
# Ignore everything in the scripts directory.
bump-pydantic --ignore=scripts/** .
# Ignore only files in the tests directory, but don't ignore more deeply nested files.
bump-pydantic --ignore=tests/* .
# Ignore only files under directories named foo.
bump-pydantic --ignore=**/foo/* .
# Ignore all __init__.py files.
bump-pydantic --ignore=**/__init__.py .
```

## Implementation details and design decisions

- This PR adds a function `glob_to_re()` which translates a glob pattern into a regular expression. The function is necessary because:
  - the `glob` module does not provide a way to match a path against a pattern without traversing the file system, and
  - the `fnmatch.fnmatch()` and `pathlib.Path.match()` functions do not handle recursive wildcards (`**`).
 
- This feature requires disabling automatic argument expansion on Windows in Click. If not disabled, option strings like `.venv/**` will be transformed into `.venv\\` before bump-pydantic is able to apply its own interpretation of the string. The only way to pass this argument to Click is during the invocation of the app instance, therefore it was necessary to use `functools.partial`.

- Extra: a list of default ignore patterns has been added, currently only containing `.venv/**`.

- Extra: if no files are left either because there are no source files in the given directory, or as a result of filtering with ignore patterns, the program now exits gracefully instead of having Mypy raise an error.

2023-07-14 12:47 UTC, Kludex requested changes
Can we add some unit tests for `glob_to_re`?

2023-07-14 18:24 UTC, lemonyte commented on bump_pydantic/main.py
> +entrypoint = functools.partial(app, windows_expand_args=False)
Neither Typer nor Click seem to have an option to pass this argument during initialization. The only way to pass it is during invocation of the app through the `__call__()` or `main()` methods.

2023-07-17 16:54 UTC, Kludex commented on bump_pydantic/main.py
> +entrypoint = functools.partial(app, windows_expand_args=False)
Do you have a reference for this?

2023-07-17 16:55 UTC, Kludex requested changes

2023-07-17 16:55 UTC, Kludex commented on bump_pydantic/helpers.py
Can we have a meaningful name instead of "helpers"?

2023-07-17 17:46 UTC, lemonyte commented on bump_pydantic/main.py
> +entrypoint = functools.partial(app, windows_expand_args=False)
PR https://github.com/pallets/click/pull/1918 added the parameter, only to the `main` method.
The only mention of this parameter in Click's documentation is under the `main` method [here](https://click.palletsprojects.com/en/8.1.x/api/#click.BaseCommand.main).

2023-07-17 20:39 UTC, lemonyte commented on bump_pydantic/helpers.py
Renamed to "glob_helpers".

2023-07-18 05:39 UTC, Kludex approved these changes
Thanks @lemonyte :)

2023-07-18 05:41 UTC, merged